$kind: http-request
method: GET
url: '{{baseUrl}}/inventory/:id/stock-history'
order: 7000
headers:
  - key: Authorization
    value: 'Bearer {{token}}'
pathVariables:
  - key: id
    value: '{{$randomUUID}}'