services:
  metabase:
    image: metabase/metabase:latest
    container_name: deyon_metabase
    ports:
      - "3001:3000"
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: h2
      MB_DB_FILE: /metabase-data/metabase.db
    restart: unless-stopped

volumes:
  metabase_data:
