sonar.projectKey=deyon-core
sonar.projectName=Deyon Core
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts,**/*.test.ts
sonar.text.exclusions=**/.env
sonar.typescript.lcov.reportPaths=coverage/lcov.info
