sonar.projectKey=deyon-core
sonar.projectName=Deyon Core
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,**/*.spec.ts,**/*.test.ts,src/migrations/**
sonar.text.exclusions=**/.env
sonar.coverage.exclusions=src/instrument.ts,src/main.ts,src/**/*.module.ts,src/shared/queryEngine/sqlBuilder/queryBuilder.ts,src/shared/repositories/utility/findAndPaginate.ts,src/modules/core/entities/geo.base.entity.ts,src/modules/core/entities/state.entity.ts,src/modules/core/entities/lga.entity.ts,src/shared/observability/memoryMonitor.service.ts,src/shared/observability/requestTracker.service.ts
sonar.typescript.lcov.reportPaths=coverage/unit/lcov.info
