export const PERMISSION = {
  WILDCARD: '*:*',
  ROLE: {
    CREATE: 'role:create',
    READ: 'role:read',
    UPDATE: 'role:update',
    DELETE: 'role:delete',
  },
  STAFF: {
    INVITE: 'staff:invite',
    READ: 'staff:read',
    LIST: 'staff:list',
    UPDATE: 'staff:update',
    DEACTIVATE: 'staff:deactivate',
  },
  DEPARTMENT: {
    LIST: 'department:list',
    CREATE: 'department:create',
    READ: 'department:read',
    UPDATE: 'department:update',
    DELETE: 'department:delete',
  },
  HMO_PROVIDER: {
    READ: 'hmo_provider:read',
    LIST: 'hmo_provider:list',
    CREATE: 'hmo_provider:create',
    UPDATE: 'hmo_provider:update',
  },
  PERMISSION: {
    READ: 'permission:read',
  },
  PAT: {
    GENERATE: 'pat:generate',
  },
  MEDICAL_SERVICE_CATEGORY: {
    LIST: 'medical_service_category:list',
    READ: 'medical_service_category:read',
    CREATE: 'medical_service_category:create',
    UPDATE: 'medical_service_category:update',
  },
  CODING_STANDARD: {
    LIST: 'coding_standard:list',
    READ: 'coding_standard:read',
    CREATE: 'coding_standard:create',
    UPDATE: 'coding_standard:update',
  },
  MEDICAL_CODE: {
    LIST: 'medical_code:list',
    READ: 'medical_code:read',
    CREATE: 'medical_code:create',
    UPDATE: 'medical_code:update',
    DELETE: 'medical_code:delete',
  },
  SUPPLIER: {
    LIST: 'supplier:list',
    READ: 'supplier:read',
    CREATE: 'supplier:create',
    UPDATE: 'supplier:update',
  },
  INVENTORY_CATEGORY: {
    LIST: 'inventory_category:list',
    READ: 'inventory_category:read',
    CREATE: 'inventory_category:create',
    UPDATE: 'inventory_category:update',
  },
  PARTNER_LAB: {
    LIST: 'partner_lab:list',
    READ: 'partner_lab:read',
    CREATE: 'partner_lab:create',
    UPDATE: 'partner_lab:update',
  },
  SHIFT_SCHEDULE: {
    LIST: 'shift_schedule:list',
    READ: 'shift_schedule:read',
    CREATE: 'shift_schedule:create',
    UPDATE: 'shift_schedule:update',
    DELETE: 'shift_schedule:delete',
  },
  MEDICAL_SERVICE: {
    LIST: 'medical_service:list',
    READ: 'medical_service:read',
    CREATE: 'medical_service:create',
    UPDATE: 'medical_service:update',
    APPROVE: 'medical_service:approve',
  },
  PRICE_CHANGE: {
    LIST: 'price_change:list',
    READ: 'price_change:read',
    CREATE: 'price_change:create',
    APPROVE: 'price_change:approve',
  },
  SERVICE_CODE_CATALOG: {
    LIST: 'service_code_catalog:list',
    READ: 'service_code_catalog:read',
    CREATE: 'service_code_catalog:create',
    DELETE: 'service_code_catalog:delete',
  },
  INVENTORY: {
    LIST: 'inventory:list',
    READ: 'inventory:read',
    CREATE: 'inventory:create',
    UPDATE: 'inventory:update',
    ADJUST: 'inventory:adjust',
  },
  HMO_CONTRACT: {
    LIST: 'hmo_contract:list',
    READ: 'hmo_contract:read',
    CREATE: 'hmo_contract:create',
    UPDATE: 'hmo_contract:update',
    DELETE: 'hmo_contract:delete',
  },
  HMO_RULE: {
    LIST: 'hmo_rule:list',
    READ: 'hmo_rule:read',
    CREATE: 'hmo_rule:create',
    UPDATE: 'hmo_rule:update',
    DELETE: 'hmo_rule:delete',
  },
  TEST_CATALOG: {
    LIST: 'test_catalog:list',
    READ: 'test_catalog:read',
    CREATE: 'test_catalog:create',
    UPDATE: 'test_catalog:update',
  },
  REFERENCE_RANGE: {
    LIST: 'reference_range:list',
    READ: 'reference_range:read',
    CREATE: 'reference_range:create',
    UPDATE: 'reference_range:update',
    DELETE: 'reference_range:delete',
  },
  PROTOCOL_BUNDLE: {
    LIST: 'protocol_bundle:list',
    READ: 'protocol_bundle:read',
    CREATE: 'protocol_bundle:create',
    UPDATE: 'protocol_bundle:update',
    DELETE: 'protocol_bundle:delete',
  },
  PATIENT: {
    LIST: 'patient:list',
    READ: 'patient:read',
    CREATE: 'patient:create',
    UPDATE: 'patient:update',
    DELETE: 'patient:delete',
    ENROLL_HMO: 'patient:enroll_hmo',
    MANAGE_HISTORY: 'patient:manage_history',
  },
  ROSTER: {
    LIST: 'roster:list',
    READ: 'roster:read',
    CREATE: 'roster:create',
    UPDATE: 'roster:update',
    DELETE: 'roster:delete',
    PUBLISH: 'roster:publish',
    ASSIGN: 'roster:assign',
  },
  APPOINTMENT: {
    LIST: 'appointment:list',
    READ: 'appointment:read',
    CREATE: 'appointment:create',
    UPDATE: 'appointment:update',
    CONFIRM: 'appointment:confirm',
    CHECK_IN: 'appointment:check_in',
    CANCEL: 'appointment:cancel',
    NO_SHOW: 'appointment:no_show',
  },
  EPISODE: {
    LIST: 'episode:list',
    READ: 'episode:read',
    CREATE: 'episode:create',
    UPDATE: 'episode:update',
    CLOSE: 'episode:close',
    LOCK: 'episode:lock',
    UNLOCK: 'episode:unlock',
    DIAGNOSE: 'episode:diagnose',
  },
  QUEUE: {
    LIST: 'queue:list',
    READ: 'queue:read',
    CREATE: 'queue:create',
    CALL: 'queue:call',
    START: 'queue:start',
    COMPLETE: 'queue:complete',
    REMOVE: 'queue:remove',
  },
  VITAL_SIGNS: {
    LIST: 'vital_signs:list',
    READ: 'vital_signs:read',
    CREATE: 'vital_signs:create',
  },
  CONSULTATION: {
    LIST: 'consultation:list',
    READ: 'consultation:read',
    CREATE: 'consultation:create',
    UPDATE: 'consultation:update',
    START: 'consultation:start',
    FINALIZE: 'consultation:finalize',
    AMEND: 'consultation:amend',
    DELETE: 'consultation:delete',
  },
  LAB_ORDER: {
    LIST: 'lab_order:list',
    READ: 'lab_order:read',
    CREATE: 'lab_order:create',
    COLLECT_SAMPLE: 'lab_order:collect_sample',
    PROCESS: 'lab_order:process',
    ENTER_RESULT: 'lab_order:enter_result',
    COMPLETE: 'lab_order:complete',
    CANCEL: 'lab_order:cancel',
  },
  PRESCRIPTION: {
    LIST: 'prescription:list',
    READ: 'prescription:read',
    CREATE: 'prescription:create',
    DISPENSE: 'prescription:dispense',
    MARK_UNFULFILLABLE: 'prescription:mark_unfulfillable',
  },
  BILLING: {
    LIST: 'billing:list',
    READ: 'billing:read',
    CREATE: 'billing:create',
    MANAGE_ITEMS: 'billing:manage_items',
    RECORD_PAYMENT: 'billing:record_payment',
    REFUND: 'billing:refund',
    GENERATE_CODE: 'billing:generate_code',
    VALIDATE_CODE: 'billing:validate_code',
  },
  CLAIM: {
    LIST: 'claim:list',
    READ: 'claim:read',
    CREATE: 'claim:create',
    UPDATE: 'claim:update',
    SUBMIT: 'claim:submit',
    APPROVE: 'claim:approve',
    DENY: 'claim:deny',
    WITHDRAW: 'claim:withdraw',
    RETRACT: 'claim:retract',
    RESUBMIT: 'claim:resubmit',
    UPLOAD_DOCUMENT: 'claim:upload_document',
  },
  SHIFT: {
    LIST: 'shift:list',
    READ: 'shift:read',
    OPEN: 'shift:open',
    CLOSE: 'shift:close',
  },
  STOCK_REQUEST: {
    LIST: 'stock_request:list',
    READ: 'stock_request:read',
    CREATE: 'stock_request:create',
    APPROVE: 'stock_request:approve',
    REJECT: 'stock_request:reject',
    ESCALATE: 'stock_request:escalate',
    REQUEST_INFO: 'stock_request:request_info',
    PROVIDE_INFO: 'stock_request:provide_info',
  },
  LAB_REFERRAL: {
    LIST: 'lab_referral:list',
    READ: 'lab_referral:read',
    CREATE: 'lab_referral:create',
    DISPATCH: 'lab_referral:dispatch',
    RECEIVE_RESULTS: 'lab_referral:receive_results',
    COMPLETE: 'lab_referral:complete',
  },
  NOTIFICATION: {
    LIST: 'notification:list',
    READ: 'notification:read',
    DELETE: 'notification:delete',
  },
  AUDIT: {
    LIST: 'audit:list',
    READ: 'audit:read',
  },
  REPORT: {
    FINANCIAL: 'report:financial',
    CONSULTATIONS: 'report:consultations',
    LAB: 'report:lab',
    PHARMACY: 'report:pharmacy',
    INVENTORY: 'report:inventory',
    CLAIMS: 'report:claims',
    ALERTS: 'report:alerts',
  },
  PERMISSIONS_MGMT: {
    READ: 'permissions_mgmt:read',
    GRANT: 'permissions_mgmt:grant',
    REVOKE: 'permissions_mgmt:revoke',
  },
} as const;
