export const PERMISSION = {
  WILDCARD: '*:*',
  ROLE: {
    CREATE: 'role:create',
    READ: 'role:read',
    UPDATE: 'role:update',
    DELETE: 'role:delete',
  },
  STAFF: {
    INVITE: 'staff:invite',
    READ: 'staff:read',
    LIST: 'staff:list',
    UPDATE: 'staff:update',
    DEACTIVATE: 'staff:deactivate',
  },
  DEPARTMENT: {
    LIST: 'department:list',
    CREATE: 'department:create',
    READ: 'department:read',
    UPDATE: 'department:update',
    DELETE: 'department:delete',
  },
  HMO_PROVIDER: {
    READ: 'hmo_provider:read',
    LIST: 'hmo_provider:list',
    CREATE: 'hmo_provider:create',
    UPDATE: 'hmo_provider:update',
  },
  PERMISSION: {
    READ: 'permission:read',
  },
  PAT: {
    GENERATE: 'pat:generate',
  },
  MEDICAL_SERVICE_CATEGORY: {
    LIST: 'medical_service_category:list',
    READ: 'medical_service_category:read',
    CREATE: 'medical_service_category:create',
    UPDATE: 'medical_service_category:update',
  },
  CODING_STANDARD: {
    LIST: 'coding_standard:list',
    READ: 'coding_standard:read',
    CREATE: 'coding_standard:create',
    UPDATE: 'coding_standard:update',
  },
  MEDICAL_CODE: {
    LIST: 'medical_code:list',
    READ: 'medical_code:read',
    CREATE: 'medical_code:create',
    UPDATE: 'medical_code:update',
    DELETE: 'medical_code:delete',
  },
  SUPPLIER: {
    LIST: 'supplier:list',
    READ: 'supplier:read',
    CREATE: 'supplier:create',
    UPDATE: 'supplier:update',
  },
  INVENTORY_CATEGORY: {
    LIST: 'inventory_category:list',
    READ: 'inventory_category:read',
    CREATE: 'inventory_category:create',
    UPDATE: 'inventory_category:update',
  },
  PARTNER_LAB: {
    LIST: 'partner_lab:list',
    READ: 'partner_lab:read',
    CREATE: 'partner_lab:create',
    UPDATE: 'partner_lab:update',
  },
  SHIFT_SCHEDULE: {
    LIST: 'shift_schedule:list',
    READ: 'shift_schedule:read',
    CREATE: 'shift_schedule:create',
    UPDATE: 'shift_schedule:update',
    DELETE: 'shift_schedule:delete',
  },
  MEDICAL_SERVICE: {
    LIST: 'medical_service:list',
    READ: 'medical_service:read',
    CREATE: 'medical_service:create',
    UPDATE: 'medical_service:update',
    APPROVE: 'medical_service:approve',
  },
  PRICE_CHANGE: {
    LIST: 'price_change:list',
    READ: 'price_change:read',
    CREATE: 'price_change:create',
    APPROVE: 'price_change:approve',
  },
  SERVICE_CODE_CATALOG: {
    LIST: 'service_code_catalog:list',
    READ: 'service_code_catalog:read',
    CREATE: 'service_code_catalog:create',
    DELETE: 'service_code_catalog:delete',
  },
  INVENTORY: {
    LIST: 'inventory:list',
    READ: 'inventory:read',
    CREATE: 'inventory:create',
    UPDATE: 'inventory:update',
    ADJUST: 'inventory:adjust',
  },
  HMO_CONTRACT: {
    LIST: 'hmo_contract:list',
    READ: 'hmo_contract:read',
    CREATE: 'hmo_contract:create',
    UPDATE: 'hmo_contract:update',
    DELETE: 'hmo_contract:delete',
  },
  HMO_RULE: {
    LIST: 'hmo_rule:list',
    READ: 'hmo_rule:read',
    CREATE: 'hmo_rule:create',
    UPDATE: 'hmo_rule:update',
    DELETE: 'hmo_rule:delete',
  },
  TEST_CATALOG: {
    LIST: 'test_catalog:list',
    READ: 'test_catalog:read',
    CREATE: 'test_catalog:create',
    UPDATE: 'test_catalog:update',
  },
  REFERENCE_RANGE: {
    LIST: 'reference_range:list',
    READ: 'reference_range:read',
    CREATE: 'reference_range:create',
    UPDATE: 'reference_range:update',
    DELETE: 'reference_range:delete',
  },
  PROTOCOL_BUNDLE: {
    LIST: 'protocol_bundle:list',
    READ: 'protocol_bundle:read',
    CREATE: 'protocol_bundle:create',
    UPDATE: 'protocol_bundle:update',
    DELETE: 'protocol_bundle:delete',
  },
} as const;
