import { EntityQueryConfig } from '@shared/queryEngine';
import { Staff } from '../core/entities/staff.entity';

export const STAFF_QUERY_CONFIG: EntityQueryConfig<Staff> = {
  allowedFilters: [
    'id',
    'firstName',
    'lastName',
    'email',
    'phoneNumber',
    'licenseNumber',
    'specialization',
    'isApproved',
    'isActive',
    'roleId',
    'departmentId',
    'createdAt',
    'updatedAt',
    'role.name',
    'role.alias',
    'role.isActive',
    'department.name',
    'department.alias',
  ],
  allowedSort: [
    'firstName',
    'lastName',
    'email',
    'createdAt',
    'updatedAt',
    'isActive',
    'isApproved',
  ],
  allowedSearch: [
    { field: 'firstName', type: 'fts' },
    { field: 'firstName', type: 'tri' },
    { field: 'lastName', type: 'fts' },
    { field: 'lastName', type: 'tri' },
    { field: 'email', type: 'tri' },
  ],
  allowedRelations: ['role', 'department'],
  allowedFields: [
    'id',
    'firstName',
    'lastName',
    'email',
    'phoneNumber',
    'licenseNumber',
    'specialization',
    'isApproved',
    'isActive',
    'lastLogin',
    'roleId',
    'departmentId',
    'createdAt',
    'updatedAt',
    'role.name',
    'role.alias',
    'department.name',
    'department.alias',
  ],
  maxRelationDepth: 1,
  cacheTtlSeconds: 30,
};
