import { Entity, Column, Index } from 'typeorm';
import { BaseEntity } from '@shared/repositories/base.entity';

export enum EventType {
  HMO_PROVIDER_CREATED = 'HMO_PROVIDER_CREATED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGIN_LOCKED = 'LOGIN_LOCKED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  MFA_FAILED = 'MFA_FAILED',
  MFA_BACKUP_USED = 'MFA_BACKUP_USED',
  MFA_SETUP = 'MFA_SETUP',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  TOKEN_THEFT_DETECTED = 'TOKEN_THEFT_DETECTED',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  INVITE_SENT = 'INVITE_SENT',
  INVITE_ACCEPTED = 'INVITE_ACCEPTED',
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  STAFF_ROLE_REASSIGNED = 'STAFF_ROLE_REASSIGNED',
  CMO_REGISTERED = 'CMO_REGISTERED',
  SETUP_COMPLETED = 'SETUP_COMPLETED',
  DEPARTMENT_CREATED = 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED',
  MEDICAL_SERVICE_CATEGORY_CREATED = 'MEDICAL_SERVICE_CATEGORY_CREATED',
  MEDICAL_SERVICE_CATEGORY_UPDATED = 'MEDICAL_SERVICE_CATEGORY_UPDATED',
  CODING_STANDARD_CREATED = 'CODING_STANDARD_CREATED',
  CODING_STANDARD_UPDATED = 'CODING_STANDARD_UPDATED',
  MEDICAL_CODE_CREATED = 'MEDICAL_CODE_CREATED',
  MEDICAL_CODE_UPDATED = 'MEDICAL_CODE_UPDATED',
  MEDICAL_CODE_DELETED = 'MEDICAL_CODE_DELETED',
  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_STATUS_CHANGED = 'SUPPLIER_STATUS_CHANGED',
  INVENTORY_CATEGORY_CREATED = 'INVENTORY_CATEGORY_CREATED',
  INVENTORY_CATEGORY_UPDATED = 'INVENTORY_CATEGORY_UPDATED',
  PARTNER_LAB_CREATED = 'PARTNER_LAB_CREATED',
  PARTNER_LAB_UPDATED = 'PARTNER_LAB_UPDATED',
  PARTNER_LAB_STATUS_CHANGED = 'PARTNER_LAB_STATUS_CHANGED',
  SHIFT_SCHEDULE_CREATED = 'SHIFT_SCHEDULE_CREATED',
  SHIFT_SCHEDULE_UPDATED = 'SHIFT_SCHEDULE_UPDATED',
  SHIFT_SCHEDULE_DELETED = 'SHIFT_SCHEDULE_DELETED',
  MEDICAL_SERVICE_CREATED = 'MEDICAL_SERVICE_CREATED',
  MEDICAL_SERVICE_UPDATED = 'MEDICAL_SERVICE_UPDATED',
  MEDICAL_SERVICE_STATUS_CHANGED = 'MEDICAL_SERVICE_STATUS_CHANGED',
  MEDICAL_SERVICE_APPROVED = 'MEDICAL_SERVICE_APPROVED',
  MEDICAL_SERVICE_REJECTED = 'MEDICAL_SERVICE_REJECTED',
  PRICE_CHANGE_REQUESTED = 'PRICE_CHANGE_REQUESTED',
  PRICE_CHANGE_APPROVED = 'PRICE_CHANGE_APPROVED',
  PRICE_CHANGE_REJECTED = 'PRICE_CHANGE_REJECTED',
  SERVICE_CODE_CATALOG_CREATED = 'SERVICE_CODE_CATALOG_CREATED',
  SERVICE_CODE_CATALOG_DELETED = 'SERVICE_CODE_CATALOG_DELETED',
  INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED',
  INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED',
  INVENTORY_STOCK_ADJUSTED = 'INVENTORY_STOCK_ADJUSTED',
  HMO_CONTRACT_CREATED = 'HMO_CONTRACT_CREATED',
  HMO_CONTRACT_UPDATED = 'HMO_CONTRACT_UPDATED',
  HMO_CONTRACT_STATUS_CHANGED = 'HMO_CONTRACT_STATUS_CHANGED',
  HMO_CONTRACT_DELETED = 'HMO_CONTRACT_DELETED',
  HMO_RULE_CREATED = 'HMO_RULE_CREATED',
  HMO_RULE_UPDATED = 'HMO_RULE_UPDATED',
  HMO_RULE_DELETED = 'HMO_RULE_DELETED',
  TEST_CATALOG_CREATED = 'TEST_CATALOG_CREATED',
  TEST_CATALOG_UPDATED = 'TEST_CATALOG_UPDATED',
  TEST_CATALOG_STATUS_CHANGED = 'TEST_CATALOG_STATUS_CHANGED',
  REFERENCE_RANGE_CREATED = 'REFERENCE_RANGE_CREATED',
  REFERENCE_RANGE_UPDATED = 'REFERENCE_RANGE_UPDATED',
  REFERENCE_RANGE_DELETED = 'REFERENCE_RANGE_DELETED',
  PROTOCOL_BUNDLE_CREATED = 'PROTOCOL_BUNDLE_CREATED',
  PROTOCOL_BUNDLE_UPDATED = 'PROTOCOL_BUNDLE_UPDATED',
  PROTOCOL_BUNDLE_DELETED = 'PROTOCOL_BUNDLE_DELETED',
  PROTOCOL_BUNDLE_ITEM_ADDED = 'PROTOCOL_BUNDLE_ITEM_ADDED',
  PROTOCOL_BUNDLE_ITEM_REMOVED = 'PROTOCOL_BUNDLE_ITEM_REMOVED',
  STAFF_UPDATED = 'STAFF_UPDATED',
  STAFF_DELETED = 'STAFF_DELETED',
}

export enum EventModule {
  AUTH = 'permissions',
  SETUP = 'setup',
  HMO_PROVIDER = 'hmo_provider',
  DEPARTMENT = 'department',
  MEDICAL_SERVICE_CATEGORY = 'medical_service_category',
  CODING_STANDARD = 'coding_standard',
  MEDICAL_CODE = 'medical_code',
  SUPPLIER = 'supplier',
  INVENTORY_CATEGORY = 'inventory_category',
  PARTNER_LAB = 'partner_lab',
  SHIFT_SCHEDULE = 'shift_schedule',
  MEDICAL_SERVICE = 'medical_service',
  PRICE_CHANGE = 'price_change',
  SERVICE_CODE_CATALOG = 'service_code_catalog',
  INVENTORY = 'inventory',
  HMO_CONTRACT = 'hmo_contract',
  HMO_RULE = 'hmo_rule',
  TEST_CATALOG = 'test_catalog',
  REFERENCE_RANGE = 'reference_range',
  PROTOCOL_BUNDLE = 'protocol_bundle',
  STAFF = 'staff',
}

@Entity()
export class EventLog extends BaseEntity {
  @Column({ type: 'uuid', nullable: true })
  @Index()
  actorId: string | null;

  @Column({ type: 'varchar' })
  event: EventType;

  @Column({ type: 'varchar', nullable: true })
  module: EventModule | null;

  @Column({ type: 'varchar', nullable: true })
  ipAddress: string;

  @Column({ type: 'varchar', nullable: true })
  userAgent: string;

  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, unknown>;

  @Column({ type: 'boolean', default: true })
  success: boolean;
}
