import { Entity, Column, Index } from 'typeorm';
import { BaseEntity } from '@shared/repositories/base.entity';

export enum EventType {
  HMO_PROVIDER_CREATED = 'HMO_PROVIDER_CREATED',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGIN_LOCKED = 'LOGIN_LOCKED',
  MFA_VERIFIED = 'MFA_VERIFIED',
  MFA_FAILED = 'MFA_FAILED',
  MFA_BACKUP_USED = 'MFA_BACKUP_USED',
  MFA_SETUP = 'MFA_SETUP',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  TOKEN_THEFT_DETECTED = 'TOKEN_THEFT_DETECTED',
  LOGOUT = 'LOGOUT',
  LOGOUT_ALL = 'LOGOUT_ALL',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  PASSWORD_RESET_COMPLETED = 'PASSWORD_RESET_COMPLETED',
  INVITE_SENT = 'INVITE_SENT',
  INVITE_ACCEPTED = 'INVITE_ACCEPTED',
  ROLE_CREATED = 'ROLE_CREATED',
  ROLE_UPDATED = 'ROLE_UPDATED',
  ROLE_DELETED = 'ROLE_DELETED',
  STAFF_ROLE_REASSIGNED = 'STAFF_ROLE_REASSIGNED',
  CMO_REGISTERED = 'CMO_REGISTERED',
  SETUP_COMPLETED = 'SETUP_COMPLETED',
  DEPARTMENT_CREATED = 'DEPARTMENT_CREATED',
  DEPARTMENT_UPDATED = 'DEPARTMENT_UPDATED',
  MEDICAL_SERVICE_CATEGORY_CREATED = 'MEDICAL_SERVICE_CATEGORY_CREATED',
  MEDICAL_SERVICE_CATEGORY_UPDATED = 'MEDICAL_SERVICE_CATEGORY_UPDATED',
  CODING_STANDARD_CREATED = 'CODING_STANDARD_CREATED',
  CODING_STANDARD_UPDATED = 'CODING_STANDARD_UPDATED',
  MEDICAL_CODE_CREATED = 'MEDICAL_CODE_CREATED',
  MEDICAL_CODE_UPDATED = 'MEDICAL_CODE_UPDATED',
  MEDICAL_CODE_DELETED = 'MEDICAL_CODE_DELETED',
  SUPPLIER_CREATED = 'SUPPLIER_CREATED',
  SUPPLIER_UPDATED = 'SUPPLIER_UPDATED',
  SUPPLIER_STATUS_CHANGED = 'SUPPLIER_STATUS_CHANGED',
  INVENTORY_CATEGORY_CREATED = 'INVENTORY_CATEGORY_CREATED',
  INVENTORY_CATEGORY_UPDATED = 'INVENTORY_CATEGORY_UPDATED',
  PARTNER_LAB_CREATED = 'PARTNER_LAB_CREATED',
  PARTNER_LAB_UPDATED = 'PARTNER_LAB_UPDATED',
  PARTNER_LAB_STATUS_CHANGED = 'PARTNER_LAB_STATUS_CHANGED',
  SHIFT_SCHEDULE_CREATED = 'SHIFT_SCHEDULE_CREATED',
  SHIFT_SCHEDULE_UPDATED = 'SHIFT_SCHEDULE_UPDATED',
  SHIFT_SCHEDULE_DELETED = 'SHIFT_SCHEDULE_DELETED',
  MEDICAL_SERVICE_CREATED = 'MEDICAL_SERVICE_CREATED',
  MEDICAL_SERVICE_UPDATED = 'MEDICAL_SERVICE_UPDATED',
  MEDICAL_SERVICE_STATUS_CHANGED = 'MEDICAL_SERVICE_STATUS_CHANGED',
  MEDICAL_SERVICE_APPROVED = 'MEDICAL_SERVICE_APPROVED',
  MEDICAL_SERVICE_REJECTED = 'MEDICAL_SERVICE_REJECTED',
  PRICE_CHANGE_REQUESTED = 'PRICE_CHANGE_REQUESTED',
  PRICE_CHANGE_APPROVED = 'PRICE_CHANGE_APPROVED',
  PRICE_CHANGE_REJECTED = 'PRICE_CHANGE_REJECTED',
  SERVICE_CODE_CATALOG_CREATED = 'SERVICE_CODE_CATALOG_CREATED',
  SERVICE_CODE_CATALOG_DELETED = 'SERVICE_CODE_CATALOG_DELETED',
  INVENTORY_ITEM_CREATED = 'INVENTORY_ITEM_CREATED',
  INVENTORY_ITEM_UPDATED = 'INVENTORY_ITEM_UPDATED',
  INVENTORY_STOCK_ADJUSTED = 'INVENTORY_STOCK_ADJUSTED',
  HMO_CONTRACT_CREATED = 'HMO_CONTRACT_CREATED',
  HMO_CONTRACT_UPDATED = 'HMO_CONTRACT_UPDATED',
  HMO_CONTRACT_STATUS_CHANGED = 'HMO_CONTRACT_STATUS_CHANGED',
  HMO_CONTRACT_DELETED = 'HMO_CONTRACT_DELETED',
  HMO_RULE_CREATED = 'HMO_RULE_CREATED',
  HMO_RULE_UPDATED = 'HMO_RULE_UPDATED',
  HMO_RULE_DELETED = 'HMO_RULE_DELETED',
  TEST_CATALOG_CREATED = 'TEST_CATALOG_CREATED',
  TEST_CATALOG_UPDATED = 'TEST_CATALOG_UPDATED',
  TEST_CATALOG_STATUS_CHANGED = 'TEST_CATALOG_STATUS_CHANGED',
  REFERENCE_RANGE_CREATED = 'REFERENCE_RANGE_CREATED',
  REFERENCE_RANGE_UPDATED = 'REFERENCE_RANGE_UPDATED',
  REFERENCE_RANGE_DELETED = 'REFERENCE_RANGE_DELETED',
  PROTOCOL_BUNDLE_CREATED = 'PROTOCOL_BUNDLE_CREATED',
  PROTOCOL_BUNDLE_UPDATED = 'PROTOCOL_BUNDLE_UPDATED',
  PROTOCOL_BUNDLE_DELETED = 'PROTOCOL_BUNDLE_DELETED',
  PROTOCOL_BUNDLE_ITEM_ADDED = 'PROTOCOL_BUNDLE_ITEM_ADDED',
  PROTOCOL_BUNDLE_ITEM_REMOVED = 'PROTOCOL_BUNDLE_ITEM_REMOVED',
  STAFF_UPDATED = 'STAFF_UPDATED',
  STAFF_DELETED = 'STAFF_DELETED',
  // Phase 1a — Patient Management
  PATIENT_REGISTERED = 'PATIENT_REGISTERED',
  PATIENT_UPDATED = 'PATIENT_UPDATED',
  PATIENT_DELETED = 'PATIENT_DELETED',
  PATIENT_HMO_ENROLLED = 'PATIENT_HMO_ENROLLED',
  PATIENT_HISTORY_ADDED = 'PATIENT_HISTORY_ADDED',
  PATIENT_HISTORY_REMOVED = 'PATIENT_HISTORY_REMOVED',
  // Phase 1b — Roster
  ROSTER_CREATED = 'ROSTER_CREATED',
  ROSTER_PUBLISHED = 'ROSTER_PUBLISHED',
  ROSTER_UPDATED = 'ROSTER_UPDATED',
  ROSTER_DELETED = 'ROSTER_DELETED',
  ROSTER_ASSIGNMENT_ADDED = 'ROSTER_ASSIGNMENT_ADDED',
  ROSTER_ASSIGNMENT_REMOVED = 'ROSTER_ASSIGNMENT_REMOVED',
  // Phase 2a — Appointments
  APPOINTMENT_BOOKED = 'APPOINTMENT_BOOKED',
  APPOINTMENT_CONFIRMED = 'APPOINTMENT_CONFIRMED',
  APPOINTMENT_CHECKED_IN = 'APPOINTMENT_CHECKED_IN',
  APPOINTMENT_CANCELLED = 'APPOINTMENT_CANCELLED',
  APPOINTMENT_NO_SHOW = 'APPOINTMENT_NO_SHOW',
  APPOINTMENT_UPDATED = 'APPOINTMENT_UPDATED',
  // Phase 2b — Episodes
  EPISODE_OPENED = 'EPISODE_OPENED',
  EPISODE_CLOSED = 'EPISODE_CLOSED',
  EPISODE_LOCKED = 'EPISODE_LOCKED',
  EPISODE_UNLOCKED = 'EPISODE_UNLOCKED',
  EPISODE_UPDATED = 'EPISODE_UPDATED',
  EPISODE_DIAGNOSIS_ADDED = 'EPISODE_DIAGNOSIS_ADDED',
  EPISODE_DIAGNOSIS_REMOVED = 'EPISODE_DIAGNOSIS_REMOVED',
  // Phase 3a — Queue
  QUEUE_PATIENT_ADDED = 'QUEUE_PATIENT_ADDED',
  QUEUE_PATIENT_CALLED = 'QUEUE_PATIENT_CALLED',
  QUEUE_SERVICE_STARTED = 'QUEUE_SERVICE_STARTED',
  QUEUE_SERVICE_COMPLETED = 'QUEUE_SERVICE_COMPLETED',
  QUEUE_PATIENT_REMOVED = 'QUEUE_PATIENT_REMOVED',
  // Phase 3b — Vital Signs
  VITALS_RECORDED = 'VITALS_RECORDED',
  // Phase 4 — Consultations
  CONSULTATION_CREATED = 'CONSULTATION_CREATED',
  CONSULTATION_STARTED = 'CONSULTATION_STARTED',
  CONSULTATION_FINALIZED = 'CONSULTATION_FINALIZED',
  CONSULTATION_AMENDED = 'CONSULTATION_AMENDED',
  CONSULTATION_DELETED = 'CONSULTATION_DELETED',
  // Phase 5a — Lab Orders
  LAB_ORDER_CREATED = 'LAB_ORDER_CREATED',
  LAB_SAMPLE_COLLECTED = 'LAB_SAMPLE_COLLECTED',
  LAB_PROCESSING_STARTED = 'LAB_PROCESSING_STARTED',
  LAB_RESULT_ENTERED = 'LAB_RESULT_ENTERED',
  LAB_ORDER_COMPLETED = 'LAB_ORDER_COMPLETED',
  LAB_ORDER_CANCELLED = 'LAB_ORDER_CANCELLED',
  // Phase 5b — Prescriptions
  PRESCRIPTION_CREATED = 'PRESCRIPTION_CREATED',
  PRESCRIPTION_DISPENSED = 'PRESCRIPTION_DISPENSED',
  PRESCRIPTION_PARTIALLY_DISPENSED = 'PRESCRIPTION_PARTIALLY_DISPENSED',
  PRESCRIPTION_UNFULFILLABLE = 'PRESCRIPTION_UNFULFILLABLE',
  // Phase 6 — Billing & Payments
  BILL_CREATED = 'BILL_CREATED',
  BILL_ITEMS_UPDATED = 'BILL_ITEMS_UPDATED',
  BILL_PAID = 'BILL_PAID',
  BILL_PARTIALLY_PAID = 'BILL_PARTIALLY_PAID',
  BILL_REFUNDED = 'BILL_REFUNDED',
  BILLING_CODE_GENERATED = 'BILLING_CODE_GENERATED',
  // Phase 7 — HMO Claims
  CLAIM_CREATED = 'CLAIM_CREATED',
  CLAIM_UPDATED = 'CLAIM_UPDATED',
  CLAIM_SUBMITTED = 'CLAIM_SUBMITTED',
  CLAIM_DOCUMENT_UPLOADED = 'CLAIM_DOCUMENT_UPLOADED',
  CLAIM_APPROVED = 'CLAIM_APPROVED',
  CLAIM_DENIED = 'CLAIM_DENIED',
  CLAIM_PAID = 'CLAIM_PAID',
  CLAIM_WITHDRAWN = 'CLAIM_WITHDRAWN',
  CLAIM_RETRACTED = 'CLAIM_RETRACTED',
  CLAIM_RESUBMITTED = 'CLAIM_RESUBMITTED',
  // Phase 8a — Cashier Shifts
  SHIFT_OPENED = 'SHIFT_OPENED',
  SHIFT_CLOSED = 'SHIFT_CLOSED',
  // Phase 8b — Stock Requests
  STOCK_REQUEST_CREATED = 'STOCK_REQUEST_CREATED',
  STOCK_REQUEST_APPROVED = 'STOCK_REQUEST_APPROVED',
  STOCK_REQUEST_REJECTED = 'STOCK_REQUEST_REJECTED',
  STOCK_REQUEST_ESCALATED = 'STOCK_REQUEST_ESCALATED',
  STOCK_REQUEST_INFO_REQUESTED = 'STOCK_REQUEST_INFO_REQUESTED',
  STOCK_REQUEST_INFO_PROVIDED = 'STOCK_REQUEST_INFO_PROVIDED',
  // Phase 8c — Lab Referrals
  LAB_REFERRAL_CREATED = 'LAB_REFERRAL_CREATED',
  LAB_REFERRAL_DISPATCHED = 'LAB_REFERRAL_DISPATCHED',
  LAB_REFERRAL_RESULTS_RECEIVED = 'LAB_REFERRAL_RESULTS_RECEIVED',
  LAB_REFERRAL_COMPLETED = 'LAB_REFERRAL_COMPLETED',
  // Phase 9a — Notifications
  NOTIFICATION_SENT = 'NOTIFICATION_SENT',
  // Phase 9c — Permission Overrides
  PERMISSION_OVERRIDE_GRANTED = 'PERMISSION_OVERRIDE_GRANTED',
  PERMISSION_OVERRIDE_REVOKED = 'PERMISSION_OVERRIDE_REVOKED',
}

export enum EventModule {
  AUTH = 'permissions',
  SETUP = 'setup',
  HMO_PROVIDER = 'hmo_provider',
  DEPARTMENT = 'department',
  MEDICAL_SERVICE_CATEGORY = 'medical_service_category',
  CODING_STANDARD = 'coding_standard',
  MEDICAL_CODE = 'medical_code',
  SUPPLIER = 'supplier',
  INVENTORY_CATEGORY = 'inventory_category',
  PARTNER_LAB = 'partner_lab',
  SHIFT_SCHEDULE = 'shift_schedule',
  MEDICAL_SERVICE = 'medical_service',
  PRICE_CHANGE = 'price_change',
  SERVICE_CODE_CATALOG = 'service_code_catalog',
  INVENTORY = 'inventory',
  HMO_CONTRACT = 'hmo_contract',
  HMO_RULE = 'hmo_rule',
  TEST_CATALOG = 'test_catalog',
  REFERENCE_RANGE = 'reference_range',
  PROTOCOL_BUNDLE = 'protocol_bundle',
  STAFF = 'staff',
  PATIENT = 'patient',
  ROSTER = 'roster',
  APPOINTMENT = 'appointment',
  EPISODE = 'episode',
  QUEUE = 'queue',
  VITAL_SIGNS = 'vital_signs',
  CONSULTATION = 'consultation',
  LAB_ORDER = 'lab_order',
  PRESCRIPTION = 'prescription',
  BILLING = 'billing',
  CLAIM = 'claim',
  SHIFT = 'shift',
  STOCK_REQUEST = 'stock_request',
  LAB_REFERRAL = 'lab_referral',
  NOTIFICATION = 'notification',
  AUDIT = 'audit',
  REPORT = 'report',
  PERMISSIONS_MGMT = 'permissions_mgmt',
}

@Entity()
export class EventLog extends BaseEntity {
  @Column({ type: 'uuid', nullable: true })
  @Index()
  actorId: string | null;

  @Column({ type: 'varchar' })
  event: EventType;

  @Column({ type: 'varchar', nullable: true })
  module: EventModule | null;

  @Column({ type: 'varchar', nullable: true })
  ipAddress: string;

  @Column({ type: 'varchar', nullable: true })
  userAgent: string;

  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, unknown>;

  @Column({ type: 'boolean', default: true })
  success: boolean;
}
